// Компоненты веба 1:1 по классам design/ui.css. Стили — `@sosed/ui-web/styles.css`.
export type { AvatarPalette, AvatarProps, AvatarSize } from './Avatar.tsx';
export { Avatar, initials, paletteFor } from './Avatar.tsx';
export type { BadgeTone } from './Badge.tsx';
export { Badge } from './Badge.tsx';
export type { ButtonProps, ButtonVariant, IconButtonProps } from './Button.tsx';
export { Button, IconButton } from './Button.tsx';
export type { CardProps } from './Card.tsx';
export { Card } from './Card.tsx';
export type { ChipProps } from './Chips.tsx';
export { AvatarStack, Chip, Chips, Price } from './Chips.tsx';
export { cx } from './cx.ts';
export type { BannerTone } from './Feedback.tsx';
export { Banner, EmptyState, ProgressBar, Skeleton, Stars, Steps, Toast } from './Feedback.tsx';
export type { OptionProps, SegmentedOption } from './form/Choice.tsx';
export { Option, Segmented, Switch } from './form/Choice.tsx';
export type { FieldProps, InputProps, SearchFieldProps, TextareaProps } from './form/Field.tsx';
export { Field, Input, SearchField, Textarea } from './form/Field.tsx';
export type { RowProps } from './Group.tsx';
export { Group, Row, RowIcon, Tile, Tiles } from './Group.tsx';
export type { PhotoProps } from './Photo.tsx';
export { Photo } from './Photo.tsx';
export type { IconName, IconProps, IconSize } from './icon/Icon.tsx';
export { ICON_NAMES, Icon } from './icon/Icon.tsx';
export type { Gap } from './layout/Stack.tsx';
export { HStack, Stack } from './layout/Stack.tsx';
export type { TabBarProps, TabItem } from './TabBar.tsx';
export { TabBar } from './TabBar.tsx';
export type { HeadingProps, HeadingVariant, TextVariant } from './text/Heading.tsx';
export { Heading, SectionTitle, Text } from './text/Heading.tsx';
